# Generated by Django 5.1.14 on 2026-07-08 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='лайки', to=settings.AUTH_USER_MODEL),
        ),
    ]
